### ISSUE TITLE
Add Currency Formatting Support

### ISSUE THREAD

**Issue by bitsandbots** [bitsandbots/inventory#10]
Add Currency Formatting Support

added ./includes/formatcurrency.php

Change currency code set in ./includes/load.php

**Comment by bitsandbots** [comment]
Change currency code set in ./includes/load.php
default $CURRENCY_CODE = 'USD';

**Comment by dj-ellis** [comment]
Good evening,

Many thanks for this update.  Initial tests have highlighted the following:

1. On sign-in, currency values on home page default to USD, updating on screen change.

2. Dashboard screen - summary boxes at the top are mis-sizing. Image attached.

<img width="1045" alt="Screenshot 2020-10-23 at 23 07 11" src="https://user-images.githubusercontent.com/59521908/97058379-91730500-1585-11eb-9541-e9c3041e0f5e.png">

3. Sales by Date report displays a warning, (Notice: Trying to access array offset on value of type bool in {path}/includes/sql.php on line 225) and defaults to USD currency.


Will keep testing!

**Comment by dj-ellis** [comment]
New Error:  Notice: A non well formed numeric value encountered in /includes/formatcurrency.php on line 127
£1.00

Replicated with any sales value over £1000 / $1000

**Comment by dj-ellis** [comment]
Latest update tested. Errors as follows:

1. When running Sales Report, if no sales for the dates entered, error returned as follows:

_NOTICE: UNDEFINED VARIABLE: PROFIT IN /INCLUDES/FUNCTIONS.PHP ON LINE 83_

2. Manage Orders page: does not resize table to fit width of window.  (3/4 on a full-width browser window)
