### ISSUE TITLE
Product Inventory Report Request

### ISSUE THREAD

**Issue by dj-ellis** [bitsandbots/inventory#12]
Hi,

Would it be possible to develop a product inventory report, similar to sales reports, with parameters as follows:

List all product inventory - Product ID, Name, Category, Price, Quantity

with options for all inventory, or by category from a drop-down list?

Thanks

**Comment by bitsandbots** [comment]
Please download the latest release.
Click the Sales by date report.
Change the URL from /inventory/sales_report.php to /inventory/stock_report.php
Let me know if this works and we can add it to the menu.

**Comment by dj-ellis** [comment]
All works - thank you!

- Addition of "Location" field into Stock report would be useful for final version.

- Recommend a new sub-menu: Reports - consolidate all current (2) and possible future reports into this menu.
 
- Addition of version control / version number to header or footer for end user version tracking.
