### ISSUE TITLE
Feature Request: Order Summary Report

### ISSUE THREAD

**Issue by dj-ellis** [bitsandbots/inventory#13]
Request to add an Order Summary Report that can be used as an order summary or stock picking list:

Order Number
Customer Name
Date
Product
Quantity

I see this as working in the same way as the sales does now – select the order on the “manage Orders” page, and then when clicking the report, it carries the order number forward…

**Comment by dj-ellis** [comment]
There appears to be an error in the calculations on the "Sales Invoice" report:

The price column appears to be correctly displaying the total calculated price from the "Sales by Order" page but then multiplying this total by the quantity to give an incorrect figure.

Example below:

David

<img width="1014" alt="Screenshot 2020-11-20 at 16 52 29" src="https://user-images.githubusercontent.com/59521908/99828354-c0fc3980-2b52-11eb-9714-d08cd435a55d.png">

**Comment by bitsandbots** [comment]
Probably should add Order Number?

**Comment by dj-ellis** [comment]
That would be ideal…

David
