### ISSUE TITLE
Feature Request: Add Sale functions

### ISSUE THREAD

**Issue by dj-ellis** [bitsandbots/inventory#14]
Request to add the "in-stock" quantity as a number to the Add Sale pages:

“add_sale_to_order.php” 
“add_sale.php”

This allows an informed decision on stock to add to the sale whilst editing it.

**Comment by bitsandbots** [comment]
I labeled it "available", would you prefer "in-stock"?

**Comment by dj-ellis** [comment]
Hi... either works - available keeps it quite generic - so it can apply to stock, consumables or equipment, depending on the user need...

Many thanks

David


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dj-ellis** [comment]
All working - and very useful.

Would it be easy enough to add "Location" to this page also - so that it is easy to identify how may items available and where to look for them?

**Comment by bitsandbots** [comment]
Yes, I forgot you mentioned that request.  Good reason for us to use this tracking system :-)

**Comment by bitsandbots** [comment]
Do we need the add_sales.php?

**Comment by dj-ellis** [comment]
In general?

It’s quite useful as it has the search function integrated…

I see it being used dependent upon the user level – basic users for example can search for products, experienced users can use the alternative route via Manage Orders…

I’ll keep testing – and let you know my thoughts…

I’m also just starting a write up of a user manual – aimed at the end user – if that helps…

D

**Comment by bitsandbots** [comment]
sounds good!

**Comment by dj-ellis** [comment]
Couple of lines added to the error_log on my install as follows:

- [19-Nov-2020 20:00:35 UTC] PHP Warning:  addslashes() expects exactly 1 parameter, 0 given in /ajax.php on line 26

- [19-Nov-2020 20:00 43 UTC] PHP Warning:  Use of undefined constant quantity - assumed 'quantity' (this will throw an Error in a future version of PHP) in /add_sale.php on line 25


- [19-Nov-2020 20:01:04 UTC] PHP Notice:  Undefined index: date in /add_sale_to_order.php on line 38

The last one seems to cause an issue - redirecting to a "Forbidden" error - and requiring a restart of the browser...  No other impacts noted at present...
