### ISSUE TITLE
site wont open php parse error

### ISSUE THREAD

**Issue by sirionnetworks** [bitsandbots/inventory#16]
site wont open:

error message in apache log :  PHP Parse error:  syntax error, unexpected '.', expecting ',' or ';' in /var/www/https/inventory/includes/upload.php on line 16

seems that SITE ROOT DS is not defined ? 

 public $userPath = SITE_ROOT.DS.'..'.DS.'/uploads/users';

**Comment by bitsandbots** [comment]
Most likely this is a permissions issue.  Try changing the permissions of the upload directory to 777.
