### ISSUE TITLE
stuck on .com/auth.php

### ISSUE THREAD

**Issue by B1TB0Y01** [bitsandbots/inventory#2]
After I log in I get stuck on .com/auth.php.
Please help me.

**Comment by bitsandbots** [comment]
try http://localhost/login.php or http://127.0.0.1/login.php

**Comment by B1TB0Y01** [comment]
I uploaded the website on 000webhost. But when I try website-name.com/login.php it says "Page not found".

**Comment by bitsandbots** [comment]
There are several steps needed to install this open-source inventory management system.  Please follow the documentation.
