### ISSUE TITLE
Add Product Stock-Keeping Unit (SKU)

### ISSUE THREAD

**Issue by bitsandbots** [bitsandbots/inventory#22]
Add Product Stock-Keeping Unit (SKU) number field to the database.

Add field to:
Add to add_product.php
Add to edit_product.php
Add to view_product.php 
 minor fix - update stock icon

Add Sale - Find by SKU
Add Stock Report

**Comment by bitsandbots** [comment]
Add Sale - Find by SKU?

**Comment by dj-ellis** [comment]
Hi,

This would make sense - SKU barcode scanned, and item added to sale...

**Comment by dj-ellis** [comment]
Hi,

I can't seem to get the Add Sale by SKU feature to work...

ajax_sku.php seems to fail with a blank screen...

Also following PHP error:

24-Nov-2020 00:50:58 UTC] PHP Warning:  addslashes() expects exactly 1 parameter, 0 given in ajax.php on line 26

Thanks

David

**Comment by bitsandbots** [comment]
You might be missing the Javascript functions that are required by ajax.

**Comment by dj-ellis** [comment]
Thanks. Can you point me in the right direction?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bitsandbots** [comment]
[](https://github.com/bitsandbots/inventory/blob/master/libs/js/functions.js)

**Comment by bitsandbots** [comment]
https://github.com/bitsandbots/inventory/blob/master/libs/js/functions.js

**Comment by dj-ellis** [comment]
Thanks.  Refreshed - and seems to be ok.

Couple of observations:

- How do you routinely access "add_sale_by_sku.php"?  Can't see a menu item or link / button.
- Running through adding by SKU, clicking on : Add Sale after finding the item returns to the "add_sale.php page - which then reverts to search by product name...  (Not sure if this is avoidable?)
- Errors in my log (seem to relate to Login..):
[24-Nov-2020 01:55:40 UTC] PHP Notice:  Undefined index: username in includes/functions.php on line 35
[24-Nov-2020 01:55:40 UTC] PHP Notice:  Undefined index: username in /auth.php on line 13
[24-Nov-2020 01:55:40 UTC] PHP Notice:  Undefined index: password in /auth.php on line 14

No further errors at this time...

Thanks

D

**Comment by dj-ellis** [comment]
All updated - and working well. Thank you!
