### ISSUE TITLE
Issue: Pages not utilising currency code

### ISSUE THREAD

**Issue by dj-ellis** [bitsandbots/inventory#24]
Following pages have reverted to USD, rather than specified currency code in load.php:

- products.php
- view_product.php

Other pages that utilise currency figures don't appear to have currency code implemented. 

- sale_report_process.php
- monthly_sales.php
- daily_sales.php

stock_report_process.php still correctly displaying currency before value, as is admin.php

**Comment by bitsandbots** [comment]
I think products is good now, I'll have a look at the other pages you've listed shortly.
