### ISSUE TITLE
Issue: Customer Search on add_order.php

### ISSUE THREAD

**Issue by dj-ellis** [bitsandbots/inventory#25]
add_order.php:

- Suggestions do not appear for selection

- Page fails on click "Search"

**Comment by bitsandbots** [comment]
please double-check that you've updated libs/js/functions.js

**Comment by dj-ellis** [comment]
All resolved

**Comment by bitsandbots** [comment]
Clicking the Search button when customer not found will provide link to Add Customer

**Comment by dj-ellis** [comment]
Further issues with this process:

- Search for Customers works if the customer is in the database.
- Worked once for Customer not in database
- Now fails - displays "Not Found" in the suggestion box, but then no action when "Search" clicked.
- Intermittent "Forbidden" page - with cache clear and browser restart required.

**Comment by bitsandbots** [comment]
Please verify that you have the latest ajax_customer.php

**Comment by dj-ellis** [comment]
Have deleted ajax_customer.php and reinstalled from latest download.  Still fails - with "Forbidden" screen and no recovery.

**Comment by bitsandbots** [comment]
Do you have a matching log entry?

**Comment by dj-ellis** [comment]
No – there does not appear to be a corresponding error_log for this one…

**Comment by bitsandbots** [comment]
You are able to Search for existing customers without issue?

**Comment by dj-ellis** [comment]
Only once…

If I search for a customer, then start a new order, all works ok.

When I search for the next customer, the “Search” button does not action, and the site fails, with “Forbidden”
