### ISSUE TITLE
Bug: Add Sale by SKU Search

### ISSUE THREAD

**Issue by dj-ellis** [bitsandbots/inventory#3]
**Describe the bug**
When searching for products by SKU, only the first item is displayed where multiple products have the same SKU. (Same product stored in different locations for example)

**To Reproduce**
1. Go to 'Add Sale by SKU'
2. Search for Product SKU: e.g. '3615001002' (Five sets of this SKU in five locations)
3. Only one item shown in list

**Expected behavior**
Revise 'Add Sale by SKU" to function in the same way as 'Product Search' - for example, a search on SKU in the "Product Search" page reveals all matching entries in the database. 

**Screenshots**

<img width="1166" alt="Screenshot 2020-12-10 at 00 19 22" src="https://user-images.githubusercontent.com/59521908/101704884-a1836d00-3a7d-11eb-9f99-9be336b37805.png">

<img width="1170" alt="Screenshot 2020-12-10 at 00 20 46" src="https://user-images.githubusercontent.com/59521908/101704900-ac3e0200-3a7d-11eb-865c-947ac5a0f7d0.png">

**Desktop (please complete the following information):**
 - OS: MacOS 11.0.1
 - Browser Safari 
 - Version 14.0.1

**Comment by bitsandbots** [comment]
I updated the Add Sale [ by Product Name ] to use the Product Search functionality to Add Sale.  However, this function does not currently check the order to see if the product has previously been added.

**Comment by dj-ellis** [comment]
Latest update does not behave as expected.

Searching for product name or SKU (or partial of those) results in a message "Product Not Registered!" message when the search button is used.  

Clicking on the autosuggested product name does display results.

<img width="1176" alt="Screenshot 2020-12-11 at 14 34 15" src="https://user-images.githubusercontent.com/59521908/101917828-8f5e1780-3bc0-11eb-90bd-09ab27e94ea8.png">

**Comment by bitsandbots** [comment]
Using ajax for this process is too problematic to be worth it.   I've reworked the add sales to offer by search or category.
