### ISSUE TITLE
Feature Request: Search Products

### ISSUE THREAD

**Issue by dj-ellis** [bitsandbots/inventory#32]
Create a generic "Product Search" page - to allow full or partial search of text name, sku or description, and display all matching results to allow selection or editing.

**Comment by bitsandbots** [comment]
I've replaced the menu item, Add Product, with Product Search and moved the Add Product to the Manage Products page matching how other pages have been designed.
When searching for products, clicking the Search button without selecting a suggested product name to get multiple matching results.
