### ISSUE TITLE
Time and currency

### ISSUE THREAD

**Issue by RicardoIsidroCosta** [bitsandbots/inventory#9]
Hi, 

I would like to ask you how can I change the timezone. Where I live the timezone is +0 and I would like to change this.

Another thing that I was trying to solve but not succefully unfortunately is the currency. I would like to show in EUR and not in DOLLAR. I changed in includes/formatcurrency.php to EUR but nothing happend. 

Can you please check this please? 

Awaiting answer ;) 

Best regards

**Comment by bitsandbots** [comment]
The timestamp that is displayed is from your server that is running the application.  You would need to change your system time.  If you are unable to do this, you may want to comment out this line of source code found at /inventory/layouts/header.php
The format currency setting that needs to be changed is found at /inventory/includes/load.php after the list of included files.

**Comment by RicardoIsidroCosta** [comment]
Thank you very much for helping me. 

I have changed the source code to:

        <strong>
		<?php 
		setlocale(LC_TIME, 'pt_PT', 'pt_PT.utf-8', 'pt_PT.utf-8', 'portuguese');
		date_default_timezone_set('Europe/Lisbon');
		echo strftime('%A, %d de %B de %Y', strtotime('today'));
		echo date(" , g:i ");
		?></strong>

And now it´s okay, 

Also the currency is already in EUR, thank you.

Best regards.
